# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

default_docker: &default_docker
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *default_docker
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: node_modules
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run build
  test:
    <<: *default_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules
      - run: npm install
      - run: npm test
  analyze:
    <<: *default_docker
    steps:
      - checkout
      - run: npm audit

workflows:
  simple_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
